name: Mirror to Sub Repo

on:
  push:
    branches:
      - main   # Main-Repo branch name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Full commit history

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Push to Sub Repo
        run: |
          echo "🔗 Adding Sub Repo remote..."
          git remote add sub-repo https://x-access-token:${{ secrets.SUB_REPO_PAT }}@github.com/Sharmila127/Sub-Repo.git
          echo "🚀 Force pushing to Sub Repo..."
          git push --force sub-repo main
