name: Mirror to Sub Repo (Debug)

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Test Connection to Sub Repo
        run: |
          echo "🔍 Testing connection..."
          git remote add sub-repo https://x-access-token:${{ secrets.SUB_REPO_PAT }}@github.com/Sharmila127/Sub-Repo.git
          git ls-remote sub-repo || echo "❌ Remote connection failed"

      - name: Push to Sub Repo
        run: |
          echo "🚀 Pushing to Sub Repo..."
          git push --force sub-repo main || echo "❌ Push failed"
