name: Mirror to Sub-Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Mirror Push to Sub-Repo
        env:
          SUB_REPO_PAT: ${{ secrets.SUB_REPO_PAT }}
        run: |
          git remote add sub-repo https://x-access-token:${SUB_REPO_PAT}@github.com/Sharmila127/Sub-Repo.git
          git push --mirror sub-repo
